// Code generated by go-swagger; DO NOT EDIT.

package claim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddClaimHandlerFunc turns a function with the right signature into a add claim handler
type AddClaimHandlerFunc func(AddClaimParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddClaimHandlerFunc) Handle(params AddClaimParams) middleware.Responder {
	return fn(params)
}

// AddClaimHandler interface for that can handle valid add claim params
type AddClaimHandler interface {
	Handle(AddClaimParams) middleware.Responder
}

// NewAddClaim creates a new http.Handler for the add claim operation
func NewAddClaim(ctx *middleware.Context, handler AddClaimHandler) *AddClaim {
	return &AddClaim{Context: ctx, Handler: handler}
}

/*AddClaim swagger:route POST /cars/{carId}/policies/{policyId}/claims claim addClaim

Add a new claim to a car

*/
type AddClaim struct {
	Context *middleware.Context
	Handler AddClaimHandler
}

func (o *AddClaim) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddClaimParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
