//
// Copyright Uhuchain All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by go-swagger; DO NOT EDIT.

package rest

import (
	"crypto/tls"
	"log"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"github.com/uhuchain/uhuchain-api/interfaces/hlf"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/handler"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/operations"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/operations/car"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/operations/claim"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/operations/policy"
	"github.com/uhuchain/uhuchain-api/interfaces/rest/operations/status"
)

// This file is safe to edit. Once it exists it will not be overwritten
var requestHandler handler.RequestHandler

//go:generate swagger generate server --target .. --name uhuchain-api --spec ../swagger/swagger.yaml

func configureFlags(api *operations.UhuchainAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.UhuchainAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	// init the request handler with the hyperledger fabric client (uhu client) here
	log.Println("Initializing UHU blockchain client")
	requestHandler = handler.NewRequestHandler(&hlf.FabricClient{})

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.CarAddCarHandler = car.AddCarHandlerFunc(requestHandler.HandleAddCar)

	api.ClaimAddClaimHandler = claim.AddClaimHandlerFunc(func(params claim.AddClaimParams) middleware.Responder {
		return middleware.NotImplemented("operation claim.AddClaim has not yet been implemented")
	})
	api.PolicyAddPolicyHandler = policy.AddPolicyHandlerFunc(func(params policy.AddPolicyParams) middleware.Responder {
		return middleware.NotImplemented("operation policy.AddPolicy has not yet been implemented")
	})

	api.CarGetCarHandler = car.GetCarHandlerFunc(requestHandler.HandleGetCar)
	api.StatusGetStatusHandler = status.GetStatusHandlerFunc(requestHandler.HandleStatus)

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
