// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Uhuchain simple REST API for cars",
    "title": "Uhuchain Car API",
    "termsOfService": "http://uhuchain.com/terms/",
    "contact": {
      "email": "developers@uhuchain.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.0.1"
  },
  "host": "api.uhuchain.com",
  "basePath": "/v1",
  "paths": {
    "/cars": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "car"
        ],
        "summary": "Add a new car to the blockchain",
        "operationId": "addCar",
        "parameters": [
          {
            "description": "Car that should be added to the uhuchain",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Car"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New car created"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/cars/{carId}/policies/{policyId}/claims": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "claim"
        ],
        "summary": "Add a new claim to a car",
        "operationId": "addClaim",
        "parameters": [
          {
            "type": "integer",
            "description": "The car ID",
            "name": "carId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "description": "The policy ID",
            "name": "policyId",
            "in": "path",
            "required": true
          },
          {
            "description": "Claim that should be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Claim"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Claim was created"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/cars/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "car"
        ],
        "summary": "Get a car from uhuchain",
        "operationId": "getCar",
        "parameters": [
          {
            "type": "integer",
            "description": "The car ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Car with the given ID",
            "schema": {
              "$ref": "#/definitions/Car"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/cars/{id}/policies": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "summary": "Add a new policy to a car",
        "operationId": "addPolicy",
        "parameters": [
          {
            "type": "integer",
            "description": "The car ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Policy that should be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Policy"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Policy was created"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/status": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "Get general information about uhuchain",
        "operationId": "getStatus",
        "responses": {
          "200": {
            "description": "Status Message",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "example": "6433"
        },
        "message": {
          "type": "string",
          "example": "Something bad happend"
        },
        "type": {
          "type": "string",
          "example": "Error"
        }
      }
    },
    "Car": {
      "type": "object",
      "required": [
        "vehicleId",
        "brand",
        "model"
      ],
      "properties": {
        "brand": {
          "type": "string",
          "example": "Volkswagen"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "example": "12345"
        },
        "model": {
          "type": "string",
          "example": "Golf GTI"
        },
        "policies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Policy"
          }
        },
        "vehicleId": {
          "type": "string",
          "example": "THK34SDM6A2D34"
        }
      },
      "xml": {
        "name": "Car"
      }
    },
    "Claim": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "example": "2016-11-01"
        },
        "description": {
          "type": "string",
          "example": "Something bad happend"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "example": "12345"
        }
      },
      "xml": {
        "name": "Claim"
      }
    },
    "Policy": {
      "type": "object",
      "properties": {
        "claims": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Claim"
          }
        },
        "endDate": {
          "type": "string",
          "example": "2017-09-01"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "example": "12345"
        },
        "insuranceId": {
          "type": "integer",
          "format": "int64",
          "example": "12345"
        },
        "insuranceName": {
          "type": "string",
          "example": "Zurich Insurance Group"
        },
        "startDate": {
          "type": "string",
          "example": "2016-09-01"
        }
      },
      "xml": {
        "name": "Policy"
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    },
    "carledger_auth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://uhuchain.com/oauth/dialog",
      "scopes": {
        "read:pets": "read your cars",
        "write:pets": "modify cars in your account"
      }
    }
  },
  "tags": [
    {
      "description": "Everything about cars",
      "name": "car",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://uhuchain.com"
      }
    },
    {
      "description": "Access to policies",
      "name": "policy"
    },
    {
      "description": "Access to claims",
      "name": "claim",
      "externalDocs": {
        "description": "Find out more about Uhuchain",
        "url": "http://uhuchain.com"
      }
    }
  ],
  "externalDocs": {
    "description": "Find out more about uhuchain",
    "url": "http://uhuchain.com"
  }
}`))
}
