// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Uhuchain Car API
Uhuchain simple REST API for cars

Terms Of Service:

http://uhuchain.com/terms/


    Schemes:
      http
      https
    Host: api.uhuchain.com
    BasePath: /v1
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <developers@uhuchain.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
