// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/uhuchain/uhuchain-core/models"
)

// AddPolicyCreatedCode is the HTTP code returned for type AddPolicyCreated
const AddPolicyCreatedCode int = 201

/*AddPolicyCreated Policy was created

swagger:response addPolicyCreated
*/
type AddPolicyCreated struct {
}

// NewAddPolicyCreated creates AddPolicyCreated with default headers values
func NewAddPolicyCreated() *AddPolicyCreated {
	return &AddPolicyCreated{}
}

// WriteResponse to the client
func (o *AddPolicyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddPolicyBadRequestCode is the HTTP code returned for type AddPolicyBadRequest
const AddPolicyBadRequestCode int = 400

/*AddPolicyBadRequest Bad Request

swagger:response addPolicyBadRequest
*/
type AddPolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddPolicyBadRequest creates AddPolicyBadRequest with default headers values
func NewAddPolicyBadRequest() *AddPolicyBadRequest {
	return &AddPolicyBadRequest{}
}

// WithPayload adds the payload to the add policy bad request response
func (o *AddPolicyBadRequest) WithPayload(payload *models.APIResponse) *AddPolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add policy bad request response
func (o *AddPolicyBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddPolicyInternalServerErrorCode is the HTTP code returned for type AddPolicyInternalServerError
const AddPolicyInternalServerErrorCode int = 500

/*AddPolicyInternalServerError Server Error

swagger:response addPolicyInternalServerError
*/
type AddPolicyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddPolicyInternalServerError creates AddPolicyInternalServerError with default headers values
func NewAddPolicyInternalServerError() *AddPolicyInternalServerError {
	return &AddPolicyInternalServerError{}
}

// WithPayload adds the payload to the add policy internal server error response
func (o *AddPolicyInternalServerError) WithPayload(payload *models.APIResponse) *AddPolicyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add policy internal server error response
func (o *AddPolicyInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPolicyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
