// Code generated by go-swagger; DO NOT EDIT.

package car

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/uhuchain/uhuchain/models"
)

// AddCarCreatedCode is the HTTP code returned for type AddCarCreated
const AddCarCreatedCode int = 201

/*AddCarCreated New car created

swagger:response addCarCreated
*/
type AddCarCreated struct {
}

// NewAddCarCreated creates AddCarCreated with default headers values
func NewAddCarCreated() *AddCarCreated {
	return &AddCarCreated{}
}

// WriteResponse to the client
func (o *AddCarCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddCarMethodNotAllowedCode is the HTTP code returned for type AddCarMethodNotAllowed
const AddCarMethodNotAllowedCode int = 405

/*AddCarMethodNotAllowed Invalid input

swagger:response addCarMethodNotAllowed
*/
type AddCarMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddCarMethodNotAllowed creates AddCarMethodNotAllowed with default headers values
func NewAddCarMethodNotAllowed() *AddCarMethodNotAllowed {
	return &AddCarMethodNotAllowed{}
}

// WithPayload adds the payload to the add car method not allowed response
func (o *AddCarMethodNotAllowed) WithPayload(payload *models.APIResponse) *AddCarMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add car method not allowed response
func (o *AddCarMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCarMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
