// Code generated by go-swagger; DO NOT EDIT.

package car

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddCarHandlerFunc turns a function with the right signature into a add car handler
type AddCarHandlerFunc func(AddCarParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCarHandlerFunc) Handle(params AddCarParams) middleware.Responder {
	return fn(params)
}

// AddCarHandler interface for that can handle valid add car params
type AddCarHandler interface {
	Handle(AddCarParams) middleware.Responder
}

// NewAddCar creates a new http.Handler for the add car operation
func NewAddCar(ctx *middleware.Context, handler AddCarHandler) *AddCar {
	return &AddCar{Context: ctx, Handler: handler}
}

/*AddCar swagger:route POST /cars car addCar

Add a new car to the blockchain

*/
type AddCar struct {
	Context *middleware.Context
	Handler AddCarHandler
}

func (o *AddCar) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddCarParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
