//
// Copyright Uhuchain All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by go-swagger; DO NOT EDIT.

package car

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/uhuchain/uhuchain-api/models"
)

// GetCarOKCode is the HTTP code returned for type GetCarOK
const GetCarOKCode int = 200

/*GetCarOK Car with the given ID

swagger:response getCarOK
*/
type GetCarOK struct {

	/*
	  In: Body
	*/
	Payload *models.Car `json:"body,omitempty"`
}

// NewGetCarOK creates GetCarOK with default headers values
func NewGetCarOK() *GetCarOK {
	return &GetCarOK{}
}

// WithPayload adds the payload to the get car o k response
func (o *GetCarOK) WithPayload(payload *models.Car) *GetCarOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get car o k response
func (o *GetCarOK) SetPayload(payload *models.Car) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCarOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCarBadRequestCode is the HTTP code returned for type GetCarBadRequest
const GetCarBadRequestCode int = 400

/*GetCarBadRequest Bad Request

swagger:response getCarBadRequest
*/
type GetCarBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetCarBadRequest creates GetCarBadRequest with default headers values
func NewGetCarBadRequest() *GetCarBadRequest {
	return &GetCarBadRequest{}
}

// WithPayload adds the payload to the get car bad request response
func (o *GetCarBadRequest) WithPayload(payload *models.APIResponse) *GetCarBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get car bad request response
func (o *GetCarBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCarBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCarNotFoundCode is the HTTP code returned for type GetCarNotFound
const GetCarNotFoundCode int = 404

/*GetCarNotFound Not found

swagger:response getCarNotFound
*/
type GetCarNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetCarNotFound creates GetCarNotFound with default headers values
func NewGetCarNotFound() *GetCarNotFound {
	return &GetCarNotFound{}
}

// WithPayload adds the payload to the get car not found response
func (o *GetCarNotFound) WithPayload(payload *models.APIResponse) *GetCarNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get car not found response
func (o *GetCarNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCarNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCarInternalServerErrorCode is the HTTP code returned for type GetCarInternalServerError
const GetCarInternalServerErrorCode int = 500

/*GetCarInternalServerError Server Error

swagger:response getCarInternalServerError
*/
type GetCarInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetCarInternalServerError creates GetCarInternalServerError with default headers values
func NewGetCarInternalServerError() *GetCarInternalServerError {
	return &GetCarInternalServerError{}
}

// WithPayload adds the payload to the get car internal server error response
func (o *GetCarInternalServerError) WithPayload(payload *models.APIResponse) *GetCarInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get car internal server error response
func (o *GetCarInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCarInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
