// Code generated by go-swagger; DO NOT EDIT.

package car

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/uhuchain/uhuchain-api/core/models"
)

// AddCarCreatedCode is the HTTP code returned for type AddCarCreated
const AddCarCreatedCode int = 201

/*AddCarCreated New car created

swagger:response addCarCreated
*/
type AddCarCreated struct {
}

// NewAddCarCreated creates AddCarCreated with default headers values
func NewAddCarCreated() *AddCarCreated {
	return &AddCarCreated{}
}

// WriteResponse to the client
func (o *AddCarCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddCarBadRequestCode is the HTTP code returned for type AddCarBadRequest
const AddCarBadRequestCode int = 400

/*AddCarBadRequest Bad Request

swagger:response addCarBadRequest
*/
type AddCarBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddCarBadRequest creates AddCarBadRequest with default headers values
func NewAddCarBadRequest() *AddCarBadRequest {
	return &AddCarBadRequest{}
}

// WithPayload adds the payload to the add car bad request response
func (o *AddCarBadRequest) WithPayload(payload *models.APIResponse) *AddCarBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add car bad request response
func (o *AddCarBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCarBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddCarInternalServerErrorCode is the HTTP code returned for type AddCarInternalServerError
const AddCarInternalServerErrorCode int = 500

/*AddCarInternalServerError Server Error

swagger:response addCarInternalServerError
*/
type AddCarInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddCarInternalServerError creates AddCarInternalServerError with default headers values
func NewAddCarInternalServerError() *AddCarInternalServerError {
	return &AddCarInternalServerError{}
}

// WithPayload adds the payload to the add car internal server error response
func (o *AddCarInternalServerError) WithPayload(payload *models.APIResponse) *AddCarInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add car internal server error response
func (o *AddCarInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCarInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
